//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficialWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighScore
    {
        public int HighScoreId { get; set; }
        public string PersonId { get; set; }
        public string Score { get; set; }
        public string DateAttained { get; set; }
    }
}
